/**
 * Generate a Dockerfile for Cloud Run Jobs.
 *
 * Uses multi-stage build with isolate-package output structure.
 * The generated Dockerfile expects the build context to contain an `isolate/` directory.
 */
export function generateDockerfile(): string {
  return `# Generated by gcp-job-runner
# Multi-stage build for Cloud Run Jobs using isolate-package output

FROM node:22-slim AS base

RUN corepack enable pnpm

WORKDIR /app

COPY isolate/pnpm-lock.yaml ./
COPY isolate/pnpm-workspace.yaml ./
COPY isolate/package.json ./
COPY isolate/packages/ ./packages/
COPY isolate/dist/ ./dist/

RUN pnpm install --frozen-lockfile

FROM node:22-slim AS runner

WORKDIR /app

COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/packages ./packages
COPY --from=base /app/dist ./dist
COPY --from=base /app/package.json ./

ENTRYPOINT ["node", "--enable-source-maps", "--input-type=module", "-e", "import 'gcp-job-runner/run-cloud'"]
`;
}
